<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIU1G9N" failures="2" tests="2" name="Command line test" time="34.691" errors="0" timestamp="2024-12-11T23:59:50 IST">
  <testcase classname="tests.LoginTest" name="testInValidTitle" time="2.424">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because the return value of &amp;quot;java.lang.ThreadLocal.get()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "java.lang.ThreadLocal.get()" is null
at utils.LogManager.logToExtentReport(LogManager.java:44)
at utils.LogManager.logFail(LogManager.java:32)
at pages.BasePage.navigateToApp(BasePage.java:25)
at tests.LoginTest.testInValidTitle(LoginTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testInValidTitle -->
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.804">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because the return value of &amp;quot;java.lang.ThreadLocal.get()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "java.lang.ThreadLocal.get()" is null
at utils.LogManager.logToExtentReport(LogManager.java:44)
at utils.LogManager.logFail(LogManager.java:32)
at pages.BasePage.navigateToApp(BasePage.java:25)
at tests.LoginTest.testValidLogin(LoginTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
</testsuite> <!-- Command line test -->
